version: '3.9'

services:
  java_app:
    container_name: java_app
    image: edmund/java_app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://db.twocclkvqqyzwhsyilgu.supabase.co:5432/postgres?user=postgres&password=XKyOys06mosFjniW
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=XKyOys06mosFjniW
volumes:
  pgdata: {}